# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            T-Tasks
tagline:          'A Jekyll theme'
description:      'A simple and intuitive application designed to make managing your every-day tasks a breeze'
url:              http://teobaranga.github.io/T-Tasks
baseurl:          '/T-Tasks'

author:
  name:           'Teo Baranga'
  url:            https://twitter.com/teobaranga

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/teobaranga/t-tasks

gems: [jekyll-paginate, jekyll-gist]
